/**
 * Generates src/lib/planning/fitlab/data/foods.generated.ts from the Fit Lab catalog workbook
 * (data/fitlab/fitlab-catalogo-piatti.xlsx, sheet "Catalogo Fit Lab"). The workbook is the source of truth:
 * edit it, then run   npm run catalog:import
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import ExcelJS from 'exceljs';

const text = (v: unknown): string =>
  v && typeof v === 'object' && 'richText' in (v as object) ? (v as { richText: { text: string }[] }).richText.map((t) => t.text).join('') : String(v ?? '').trim();
const num = (v: unknown): number => {
  const n = Number(typeof v === 'object' && v && 'result' in (v as object) ? (v as { result: unknown }).result : v);
  return Number.isFinite(n) ? n : NaN;
};
const split = (s: string) => s.split(';').map((x) => x.trim()).filter(Boolean);

const MEALS: Record<string, string> = { Colazione: 'breakfast', Spuntino: 'snack', Pranzo: 'lunch', Cena: 'dinner' };
const REGIMES: Record<string, string> = { Onnivoro: 'omni', Vegetariano: 'veg', Vegano: 'vegan', Pescetariano: 'pesc' };

void (async () => {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(join(process.cwd(), 'data', 'fitlab', 'fitlab-catalogo-piatti.xlsx'));
  const ws = wb.getWorksheet('Catalogo Fit Lab')!;
  const rows: string[] = [];
  const problems: string[] = [];
  for (let r = 2; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    const id = text(row.getCell(1).value);
    const name = text(row.getCell(2).value).replace(/[’‘]/g, "'");
    if (!id || !name) continue;
    const [kcal, p, c, f, fib] = [10, 11, 12, 13, 14].map((i) => num(row.getCell(i).value));
    if ([kcal, p, c, f].some(Number.isNaN)) {
      problems.push(`${name}: valori nutrizionali mancanti`);
      continue;
    }
    const meals = split(text(row.getCell(5).value)).map((m) => MEALS[m]).filter(Boolean);
    const regimes = split(text(row.getCell(6).value)).map((m) => REGIMES[m]).filter(Boolean);
    const obj = {
      id: id.toLowerCase(),
      name,
      category: text(row.getCell(3).value),
      sub: text(row.getCell(4).value),
      meals,
      regimes,
      allergens: text(row.getCell(7).value),
      synonyms: split(text(row.getCell(8).value)).map((s) => s.replace(/[’‘]/g, "'")),
      state: text(row.getCell(9).value),
      kcal,
      p,
      c,
      f,
      fib: Number.isNaN(fib) ? 0 : fib,
    };
    rows.push('  ' + JSON.stringify(obj) + ',');
  }
  const out = `// GENERATED by scripts/catalog/import-catalog.ts from data/fitlab/fitlab-catalogo-piatti.xlsx — do not edit by hand.
// Values per 100 g in the state of \`state\` (raw / dry / cooked…); carbohydrates are available carbohydrates (no fibre).
export type FitLabCategory = 'Proteine' | 'Carboidrati' | 'Grassi' | 'Verdure' | 'Frutta' | 'Condimenti e aromi';
export type FitLabMeal = 'breakfast' | 'snack' | 'lunch' | 'dinner';
export type FitLabRegime = 'omni' | 'veg' | 'vegan' | 'pesc';

export type FitLabFood = {
  id: string;
  name: string;
  category: FitLabCategory;
  sub: string;
  meals: FitLabMeal[];
  regimes: FitLabRegime[];
  allergens: string;
  synonyms: string[];
  state: string;
  kcal: number;
  p: number;
  c: number;
  f: number;
  fib: number;
};

export const FITLAB_FOODS: FitLabFood[] = [
${rows.join('\n')}
];
`;
  writeFileSync(join(process.cwd(), 'src', 'lib', 'planning', 'fitlab', 'data', 'foods.generated.ts'), out, 'utf8');
  console.log(`Alimenti importati: ${rows.length}`);
  if (problems.length) console.log('Problemi:\n' + problems.join('\n'));
})();
