// One-off/rerunnable script: ports src/lib/mock/food-database.ts's 58-item
// FOOD_DATABASE (the canonical nutrition reference data) into
// supabase/seed.sql, which `supabase db reset` applies automatically after
// migrations on every reset. Run with `npm run supabase:seed:food` whenever
// FOOD_DATABASE changes — this file is generated, don't hand-edit the
// food_items block in seed.sql.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { FOOD_DATABASE } from '../src/lib/mock/food-database';

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const rows = FOOD_DATABASE.map(
  (f) =>
    `  (${sqlString(f.id)}, ${sqlString(f.name)}, ${sqlString(f.category)}, ${f.kcal100}, ${f.protein100}, ${f.carbs100}, ${f.fats100}, ${f.defaultPortionG})`
).join(',\n');

const sql = `-- GENERATED by scripts/seed-food-database.ts from src/lib/mock/food-database.ts.
-- Do not hand-edit — rerun \`npm run supabase:seed:food\` instead. Applied
-- automatically by \`supabase db reset\` after migrations.
insert into public.food_items (id, name, category, kcal100, protein100, carbs100, fats100, default_portion_g)
values
${rows}
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  kcal100 = excluded.kcal100,
  protein100 = excluded.protein100,
  carbs100 = excluded.carbs100,
  fats100 = excluded.fats100,
  default_portion_g = excluded.default_portion_g;
`;

const outPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql');
writeFileSync(outPath, sql, 'utf8');
console.log(`Wrote ${FOOD_DATABASE.length} food_items rows to ${outPath}`);
