/**
 * Fake-but-realistic onboarding questionnaires ("personas") — ordinary people
 * of the app's audience (16 to 60 years old, from sedentary beginners to very
 * active people with years of training). Clinical cases (obesity, celiac
 * disease, veganism, serious injuries) are deliberately NOT here: those people
 * need a dietitian/doctor and are outside the app's scope.
 *
 * Each persona is a complete `answers` blob exactly as the questionnaire
 * stores it (same ids / option values as src/lib/questionnaire/schema.ts),
 * plus what a sensible plan for them looks like. The harness (run.ts) feeds
 * them through the real plan engine and checks the output against it.
 */
export type Answers = Record<string, unknown>;

export type Persona = {
  id: string;
  name: string;
  /** One line: who they are. */
  summary: string;
  /** What a sensible plan must look like, in plain words (shown in the report). */
  expectation: string;
  answers: Answers;
  /** Extra, persona-specific hard expectations the generic checks can't know. */
  expect?: {
    /** Daily calorie target versus the person's average expenditure. */
    calories?: 'deficit' | 'surplus' | 'maintenance';
    gymSessions?: number;
    runSessions?: number;
    /** No exercise in the plan may load these areas. */
    avoidAreas?: ('knee' | 'shoulder' | 'lowerBack' | 'wrist' | 'hip')[];
    noDiet?: boolean;
    noTraining?: boolean;
    forbiddenFoodIds?: string[];
    requiredFoodIds?: string[];
  };
  /** Weight trajectory used by the closed-loop simulation (see simulate.ts); defaults to a faithful follower. */
  adherence?: { diet: number; training: number };
};

/** Fields every complete questionnaire has; personas override what differs. */
function base(overrides: Answers): Answers {
  return {
    mode: 'both',
    // Profilo fisico
    age: 30,
    sex: 'male',
    heightCm: 178,
    currentWeightKg: 78,
    // Obiettivo
    goal: 'maintainImprove',
    targetWeightKg: 78,
    // Attività quotidiana
    jobActivity: 'sedentary',
    dailySteps: '5000-8000',
    sleepHoursRange: '7-8',
    // Alimentazione
    mealsSelected: ['colazione', 'pranzo', 'cena'],
    breakfastTime: '07:30',
    lunchTime: '13:00',
    dinnerTime: '20:00',
    eatingOut: '1',
    // Preferenze
    dietaryPattern: 'none',
    allergiesIntolerances: 'No',
    excludedFoods: '',
    includedFoods: '',
    preferredProteins: ['chicken', 'eggs', 'fish', 'yogurt'],
    preferredCarbs: ['rice', 'pasta', 'oats', 'potatoes'],
    preferredFats: ['oliveOil', 'nuts'],
    coffeeIntake: '2',
    alcoholIntake: 'occasionally',
    // Allenamento
    activitiesPracticed: ['gym'],
    freq_gym: '3',
    gymExperience: '1-3years',
    gymSkillLevel: 'intermediate',
    gymSplitPreference: 'noPreference',
    focus_gym: 'hypertrophy',
    // Disponibilità
    availableDays: '3',
    sessionDuration: '45-60',
    trainingLocation: 'gym',
    // Limitazioni
    hasPain: 'no',
    cannotDoExercises: 'no',
    recentInjuries: 'no',
    ...overrides,
  };
}

export const PERSONAS: Persona[] = [
  {
    id: 'sofia-16',
    name: 'Sofia, 16 anni — studentessa, vuole tonificarsi',
    summary: 'Ragazza di 16 anni, 55 kg per 165 cm, vita da studente (sedentaria), mai fatto palestra. 2 allenamenti a settimana.',
    expectation: 'Sotto i 18 anni nessun deficit: calorie di mantenimento, proteine moderate, scheda principiante con 2 sedute full body.',
    answers: base({
      age: 16,
      sex: 'female',
      heightCm: 165,
      currentWeightKg: 55,
      goal: 'maintainImprove',
      targetWeightKg: 55,
      dailySteps: '5000-8000',
      freq_gym: '2',
      availableDays: '2',
      sessionDuration: '45-60',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'technique',
    }),
    expect: { calories: 'maintenance', gymSessions: 2 },
  },
  {
    id: 'matteo-17',
    name: 'Matteo, 17 anni — magro, vuole mettere massa',
    summary: 'Ragazzo di 17 anni, 62 kg per 176 cm, vuole arrivare a 67 kg. Principiante, 3 allenamenti a settimana.',
    expectation: 'Surplus lieve e sostenuto, proteine ~1,9 g/kg, split full body per principianti, mese di adattamento.',
    answers: base({
      age: 17,
      heightCm: 176,
      currentWeightKg: 62,
      goal: 'gainMuscle',
      targetWeightKg: 67,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      freq_gym: '3',
      availableDays: '3',
      gymExperience: '3-12months',
      gymSkillLevel: 'beginner',
      focus_gym: 'hypertrophy',
    }),
    expect: { calories: 'surplus', gymSessions: 3 },
  },
  {
    id: 'giulia-24',
    name: 'Giulia, 24 anni — vuole dimagrire qualche kg',
    summary: 'Studentessa universitaria, 62 kg per 166 cm, vuole scendere a 57 kg. Poco attiva, principiante, 3 allenamenti.',
    expectation: 'Deficit moderato, proteine alte, durata ~5-6 mesi, scheda full body principiante.',
    answers: base({
      age: 24,
      sex: 'female',
      heightCm: 166,
      currentWeightKg: 62,
      goal: 'loseFat',
      targetWeightKg: 57,
      jobActivity: 'seatedMobile',
      dailySteps: '3000-5000',
      sleepHoursRange: '6-7',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
      dietaryPattern: 'vegetarian',
      preferredProteins: ['eggs', 'yogurt', 'dairy', 'legumes'],
      preferredCarbs: ['rice', 'oats', 'bread', 'legumes', 'pasta'],
    }),
    expect: { calories: 'deficit', gymSessions: 3, forbiddenFoodIds: ['chicken-breast', 'turkey-breast', 'beef-lean', 'salmon', 'tuna-canned', 'bresaola', 'prosciutto-crudo'] },
  },
  {
    id: 'luca-22',
    name: 'Luca, 22 anni — massa muscolare, esperto',
    summary: 'Studente magro (68 kg per 180 cm), vuole arrivare a 75 kg. Esperto, 5 allenamenti a settimana da 60-90 min, 5 pasti.',
    expectation: 'Surplus controllato, proteine ~1,9 g/kg, split a 5 giorni senza mese di adattamento, progressione di carichi mese dopo mese.',
    answers: base({
      age: 22,
      heightCm: 180,
      currentWeightKg: 68,
      goal: 'gainMuscle',
      targetWeightKg: 75,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      mealsSelected: ['colazione', 'spuntinoMattina', 'pranzo', 'spuntinoPomeriggio', 'cena'],
      morningSnackTime: '10:30',
      afternoonSnackTime: '17:00',
      preferredProteins: ['chicken', 'beef', 'eggs', 'proteinPowder', 'yogurt'],
      preferredCarbs: ['rice', 'pasta', 'oats', 'potatoes', 'bread'],
      preferredFats: ['oliveOil', 'nuts', 'avocado'],
      freq_gym: '5',
      availableDays: '5',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      focus_gym: 'hypertrophy',
    }),
    expect: { calories: 'surplus', gymSessions: 5 },
  },
  {
    id: 'alessandro-29-attivo',
    name: 'Alessandro, 29 anni — molto attivo, anni di esperienza',
    summary: 'Idraulico (lavoro fisico), 80 kg per 182 cm, 12.000+ passi al giorno. Palestra 4 volte + corsa 2 volte, esperto, vuole restare in forma.',
    expectation: 'Fabbisogno alto (lavoro fisico + 6 sedute), calorie di mantenimento, alternanza sensata palestra/corsa su 6 giorni con almeno un riposo.',
    answers: base({
      age: 29,
      heightCm: 182,
      currentWeightKg: 80,
      goal: 'maintainImprove',
      targetWeightKg: 80,
      jobActivity: 'active',
      dailySteps: 'gt12000',
      activitiesPracticed: ['gym', 'running'],
      freq_gym: '4',
      freq_running: '2',
      focus_running: 'endurance',
      availableDays: '6+',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      focus_gym: 'strength',
    }),
    expect: { calories: 'maintenance' },
  },
  {
    id: 'marco-32',
    name: 'Marco, 32 anni — dimagrimento, sedentario',
    summary: 'Impiegato sedentario, 92 kg per 178 cm, vuole scendere a 82 kg. Mai fatto palestra, 3 giorni a settimana, 45-60 min.',
    expectation: 'Deficit moderato (non estremo), proteine alte ma non esagerate, durata di circa 6-9 mesi, scheda full body principiante.',
    answers: base({
      age: 32,
      heightCm: 178,
      currentWeightKg: 92,
      goal: 'loseFat',
      targetWeightKg: 82,
      jobActivity: 'sedentary',
      dailySteps: '3000-5000',
      sleepHoursRange: '6-7',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
      preferredProteins: ['chicken', 'turkey', 'eggs', 'yogurt'],
      preferredCarbs: ['rice', 'pasta', 'bread', 'oats'],
      usualBreakfast: 'cappuccino e brioche',
      usualLunch: 'pasta e pollo',
      usualDinner: 'insalata e uova',
    }),
    expect: { calories: 'deficit', gymSessions: 3 },
  },
  {
    id: 'chiara-25-ibrida',
    name: 'Chiara, 25 anni — palestra + corsa con 4 giorni disponibili',
    summary: 'Donna, 60 kg per 168 cm. Vorrebbe 3 palestra + 3 corsa ma ha solo 4 giorni disponibili. Obiettivo dimagrimento (−4 kg).',
    expectation: 'Il piano rispetta i 4 giorni disponibili, bilancia palestra e corsa, e le calorie contano l’allenamento realmente programmato.',
    answers: base({
      age: 25,
      sex: 'female',
      heightCm: 168,
      currentWeightKg: 60,
      goal: 'loseFat',
      targetWeightKg: 56,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      activitiesPracticed: ['gym', 'running'],
      freq_gym: '3',
      freq_running: '3',
      focus_running: 'fatLoss',
      focus_gym: 'fatLoss',
      availableDays: '4',
      gymExperience: '1-3years',
      gymSkillLevel: 'intermediate',
    }),
    expect: { calories: 'deficit' },
  },
  {
    id: 'paolo-38-runner',
    name: 'Paolo, 38 anni — solo corsa, resistenza',
    summary: 'Runner amatoriale, 72 kg per 176 cm. Corre 4 volte a settimana, nessuna palestra, vuole migliorare la resistenza.',
    expectation: 'Nessuna seduta di palestra, 4 uscite di corsa varie (facili, medio, lungo), carboidrati abbondanti, calorie di mantenimento.',
    answers: base({
      age: 38,
      heightCm: 176,
      currentWeightKg: 72,
      goal: 'improveEndurance',
      targetWeightKg: 72,
      jobActivity: 'standing',
      dailySteps: '8000-12000',
      activitiesPracticed: ['running'],
      freq_running: '4',
      focus_running: 'endurance',
      availableDays: '4',
      sessionDuration: '45-60',
      trainingLocation: 'outdoor',
      gymExperience: undefined,
      gymSkillLevel: undefined,
      freq_gym: undefined,
      focus_gym: undefined,
      gymSplitPreference: undefined,
    }),
    expect: { calories: 'maintenance', gymSessions: 0, runSessions: 4 },
  },
  {
    id: 'andrea-40-solo-dieta',
    name: 'Andrea, 40 anni — solo dieta',
    summary: 'Uomo, 80 kg per 180 cm, vuole solo un piano alimentare per dimagrire a 75 kg. Non usa la parte allenamento.',
    expectation: 'Il piano di allenamento non deve esistere, la dieta deve essere completa e basata su attività quotidiana.',
    answers: base({
      mode: 'diet',
      age: 40,
      heightCm: 180,
      currentWeightKg: 80,
      goal: 'loseFat',
      targetWeightKg: 75,
      jobActivity: 'sedentary',
      activitiesPracticed: undefined,
      freq_gym: undefined,
      gymExperience: undefined,
      gymSkillLevel: undefined,
      gymSplitPreference: undefined,
      focus_gym: undefined,
      availableDays: undefined,
      sessionDuration: undefined,
      trainingLocation: undefined,
      hasPain: undefined,
      cannotDoExercises: undefined,
      recentInjuries: undefined,
    }),
    expect: { calories: 'deficit', noTraining: true },
  },
  {
    id: 'ilaria-29-solo-allenamento',
    name: 'Ilaria, 29 anni — solo allenamento, forza',
    summary: 'Donna, 64 kg per 170 cm, vuole solo la scheda per aumentare la forza. 4 giorni, esperta.',
    expectation: 'Il piano alimentare non deve esistere, la scheda ha schemi di forza (poche ripetizioni, recuperi lunghi).',
    answers: base({
      mode: 'training',
      age: 29,
      sex: 'female',
      heightCm: 170,
      currentWeightKg: 64,
      goal: 'gainStrength',
      targetWeightKg: 66,
      jobActivity: 'seatedMobile',
      freq_gym: '4',
      availableDays: '4',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      focus_gym: 'strength',
      mealsSelected: undefined,
      breakfastTime: undefined,
      lunchTime: undefined,
      dinnerTime: undefined,
      eatingOut: undefined,
      dietaryPattern: undefined,
      allergiesIntolerances: undefined,
      excludedFoods: undefined,
      includedFoods: undefined,
      preferredProteins: undefined,
      preferredCarbs: undefined,
      preferredFats: undefined,
      coffeeIntake: undefined,
      alcoholIntake: undefined,
    }),
    expect: { calories: 'surplus', noDiet: true, gymSessions: 4 },
  },
  {
    id: 'anna-52',
    name: 'Anna, 52 anni — dimagrimento, sedentaria, fastidio al ginocchio',
    summary: 'Donna, 70 kg per 162 cm, vuole scendere a 64 kg. Sedentaria, principiante, 2 allenamenti. Fastidio al ginocchio quando sale le scale.',
    expectation: 'Deficit prudente, nessun esercizio che carichi il ginocchio, sedute brevi con pochi esercizi.',
    answers: base({
      age: 52,
      sex: 'female',
      heightCm: 162,
      currentWeightKg: 70,
      goal: 'loseFat',
      targetWeightKg: 64,
      jobActivity: 'sedentary',
      dailySteps: 'lt3000',
      sleepHoursRange: '5-6',
      freq_gym: '2',
      availableDays: '2',
      sessionDuration: '30-45',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
      hasPain: 'yes',
      painDetails: 'Mi fa male il ginocchio destro quando salgo le scale',
    }),
    expect: { calories: 'deficit', gymSessions: 2, avoidAreas: ['knee'] },
  },
  {
    id: 'roberto-58',
    name: 'Roberto, 58 anni — salute generale, lavoro in piedi',
    summary: 'Uomo, 82 kg per 175 cm, lavoro in piedi tutto il giorno. Vuole stare meglio. Principiante, 2 allenamenti.',
    expectation: 'Calorie di mantenimento, scheda semplice con carichi prudenti, 2 sedute.',
    answers: base({
      age: 58,
      heightCm: 175,
      currentWeightKg: 82,
      goal: 'generalHealth',
      targetWeightKg: 80,
      jobActivity: 'standing',
      dailySteps: '5000-8000',
      freq_gym: '2',
      availableDays: '2',
      sessionDuration: '30-45',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'technique',
    }),
    expect: { calories: 'maintenance', gymSessions: 2 },
  },
  {
    id: 'franco-60',
    name: 'Franco, 60 anni — pensionato, un solo giorno',
    summary: 'Uomo, 78 kg per 170 cm, pensionato. Può allenarsi 1 volta a settimana, 30 minuti, principiante.',
    expectation: 'Una sola seduta a settimana (full body, 3 esercizi), piano non invasivo, calorie di mantenimento.',
    answers: base({
      age: 60,
      heightCm: 170,
      currentWeightKg: 78,
      goal: 'generalHealth',
      targetWeightKg: 76,
      jobActivity: 'sedentary',
      dailySteps: '3000-5000',
      freq_gym: '1',
      availableDays: '1',
      sessionDuration: 'lt30',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'technique',
    }),
    expect: { calories: 'maintenance', gymSessions: 1 },
  },
  {
    id: 'tommaso-35-saltuario',
    name: 'Tommaso, 35 anni — si allena una volta ogni due settimane',
    summary: 'Uomo, 80 kg per 178 cm, mantenimento. In palestra va "una volta ogni 2 settimane" e ha 3 giorni disponibili.',
    expectation: 'Il piano programma 1 seduta a settimana (dose minima efficace) e il fabbisogno conta esattamente quella seduta.',
    answers: base({
      age: 35,
      currentWeightKg: 80,
      goal: 'maintainImprove',
      targetWeightKg: 80,
      freq_gym: 'biweekly',
      availableDays: '3',
      gymExperience: '1-3years',
      gymSkillLevel: 'intermediate',
    }),
    expect: { calories: 'maintenance', gymSessions: 1 },
  },
  {
    id: 'nina-33-senza-obiettivo-peso',
    name: 'Nina, 33 anni — dimagrimento senza peso obiettivo',
    summary: 'Donna, 70 kg per 166 cm, vuole dimagrire ma lascia vuoto il peso obiettivo (domanda facoltativa).',
    expectation: 'Nessun peso obiettivo inventato: durata standard del piano e nessun traguardo falso nelle schermate.',
    answers: base({
      age: 33,
      sex: 'female',
      heightCm: 166,
      currentWeightKg: 70,
      goal: 'loseFat',
      targetWeightKg: undefined,
      jobActivity: 'seatedMobile',
      gymExperience: '3-12months',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
    }),
    expect: { calories: 'deficit', gymSessions: 3 },
  },
  {
    id: 'omar-41-ex-allenamento',
    name: 'Omar, 41 anni — ora solo dieta, ma rimaste vecchie risposte di allenamento',
    summary: 'Uomo, 85 kg per 180 cm. Rifà il questionario scegliendo solo dieta; nelle risposte restano i dati di allenamento di prima (4 allenamenti di palestra).',
    expectation: 'Con modalità "solo dieta" le vecchie risposte di allenamento non influenzano né il fabbisogno né la dieta.',
    answers: base({
      mode: 'diet',
      age: 41,
      currentWeightKg: 85,
      goal: 'loseFat',
      targetWeightKg: 78,
      activitiesPracticed: ['gym'],
      freq_gym: '4',
      availableDays: '4',
    }),
    expect: { calories: 'deficit', noTraining: true },
  },
  {
    id: 'elena-27-lattosio',
    name: 'Elena, 27 anni — intollerante al lattosio, 5 pasti',
    summary: 'Impiegata, 62 kg per 167 cm, vuole dimagrire un po’. Intollerante al lattosio (niente yogurt, latticini, whey), colazione e due spuntini.',
    expectation: 'Senza latticini la dieta deve restare varia: colazioni e spuntini diversi ogni giorno, mai la stessa merenda per tutta la settimana.',
    answers: base({
      sex: 'female',
      age: 27,
      heightCm: 167,
      currentWeightKg: 62,
      goal: 'loseFat',
      targetWeightKg: 58,
      mealsSelected: ['colazione', 'spuntinoMattina', 'pranzo', 'spuntinoPomeriggio', 'cena'],
      morningSnackTime: '10:30',
      afternoonSnackTime: '17:00',
      allergiesIntolerances: 'intolleranza al lattosio',
    }),
    expect: { calories: 'deficit', forbiddenFoodIds: ['greek-yogurt-0', 'skyr', 'yogurt-protein', 'kefir', 'cottage-cheese', 'ricotta-magra', 'whey-protein', 'protein-pudding', 'protein-drink', 'protein-bar'] },
  },
  {
    id: 'davide-45-senza-uova-pesce',
    name: 'Davide, 45 anni — niente uova né pesce',
    summary: 'Commerciale, 84 kg per 178 cm, vuole dimagrire. Allergico alle uova e non mangia pesce; 4 pasti.',
    expectation: 'Con uova e pesce esclusi pranzi, cene e colazioni restano vari (non sempre pollo e pasta), senza ripetere lo stesso pasto più di 3 volte a settimana.',
    answers: base({
      age: 45,
      heightCm: 178,
      currentWeightKg: 84,
      goal: 'loseFat',
      targetWeightKg: 78,
      mealsSelected: ['colazione', 'pranzo', 'spuntinoPomeriggio', 'cena'],
      afternoonSnackTime: '17:00',
      allergiesIntolerances: 'allergia alle uova',
      excludedFoods: 'pesce',
    }),
    expect: { calories: 'deficit', forbiddenFoodIds: ['eggs', 'egg-whites', 'salmon', 'tuna-canned', 'cod', 'sea-bream', 'shrimp'] },
  },
  {
    id: 'paola-36-merenda-abituale',
    name: 'Paola, 36 anni — mangia sempre bresaola e avocado a merenda',
    summary: 'Insegnante, 66 kg per 170 cm. Nel questionario scrive che di solito mangia bresaola e avocado a merenda e vuole alimenti ricorrenti.',
    expectation: 'Le abitudini dichiarate orientano la scelta ma non la rendono fissa: la stessa merenda non può tornare più di 3 volte a settimana.',
    answers: base({
      sex: 'female',
      age: 36,
      heightCm: 170,
      currentWeightKg: 66,
      goal: 'maintainImprove',
      targetWeightKg: 66,
      mealsSelected: ['colazione', 'spuntinoPomeriggio', 'pranzo', 'cena'],
      afternoonSnackTime: '17:00',
      usualAfternoonSnack: 'bresaola e avocado',
      includedFoods: 'bresaola, avocado',
    }),
    expect: { calories: 'maintenance' },
  },
];
