/**
 * Fake-but-realistic onboarding questionnaires ("personas"). Each one is a
 * complete `answers` blob exactly as the app's questionnaire would store it
 * (same question ids / option values as src/lib/questionnaire/schema.ts), plus
 * a short description of who the person is and what a sensible plan for them
 * looks like — the test harness (run.ts) feeds these through the real plan
 * generators and checks the output against those expectations.
 */
export type Answers = Record<string, unknown>;

export type Persona = {
  id: string;
  name: string;
  /** One line: who they are. */
  summary: string;
  /** What a sensible plan must look like, in plain words (shown in the report). */
  expectation: string;
  answers: Answers;
  /** Extra, persona-specific hard expectations the generic checks can't know. */
  expect?: {
    /** Daily calorie target must be below / above the person's estimated TDEE. */
    calories?: 'deficit' | 'surplus' | 'maintenance';
    /** Exact number of gym sessions per week. */
    gymSessions?: number;
    /** Exact number of running sessions per week. */
    runSessions?: number;
    /** No exercise in the plan may load these areas. */
    avoidAreas?: ('knee' | 'shoulder' | 'lowerBack' | 'wrist' | 'hip')[];
    /** The plan must have no diet / no training at all (single-mode users). */
    noDiet?: boolean;
    noTraining?: boolean;
    /** Foods that must never appear in the diet. */
    forbiddenFoodIds?: string[];
    /** Foods that must appear at least once. */
    requiredFoodIds?: string[];
  };
};

/** Fields every complete questionnaire has; personas override what differs. */
function base(overrides: Answers): Answers {
  return {
    mode: 'both',
    // Profilo fisico
    age: 30,
    sex: 'male',
    heightCm: 178,
    currentWeightKg: 78,
    // Obiettivo
    goal: 'maintainImprove',
    targetWeightKg: 78,
    // Attività quotidiana
    jobActivity: 'sedentary',
    generalActivityLevel: 'occasional',
    dailySteps: '5000-8000',
    bedTime: '23:00',
    wakeTime: '07:00',
    sleepHoursRange: '7-8',
    sleepQuality: 4,
    // Alimentazione
    mealsSelected: ['colazione', 'pranzo', 'cena'],
    breakfastTime: '07:30',
    lunchTime: '13:00',
    dinnerTime: '20:00',
    eatingOut: '1',
    // Preferenze
    dietaryPattern: 'none',
    allergiesIntolerances: 'No',
    excludedFoods: '',
    includedFoods: '',
    preferredProteins: ['chicken', 'eggs', 'fish', 'yogurt'],
    preferredCarbs: ['rice', 'pasta', 'oats', 'potatoes'],
    preferredFats: ['oliveOil', 'nuts'],
    coffeeIntake: '2',
    alcoholIntake: 'occasionally',
    // Allenamento
    activitiesPracticed: ['gym'],
    freq_gym: '3',
    gymExperience: '1-3years',
    gymSkillLevel: 'intermediate',
    gymSplitPreference: 'noPreference',
    focus_gym: 'hypertrophy',
    // Disponibilità
    availableDays: '3',
    sessionDuration: '45-60',
    trainingLocation: 'gym',
    // Limitazioni
    hasPain: 'no',
    cannotDoExercises: 'no',
    recentInjuries: 'no',
    ...overrides,
  };
}

export const PERSONAS: Persona[] = [
  {
    id: 'marco-dimagrimento',
    name: 'Marco, 32 anni — dimagrimento, principiante',
    summary: 'Impiegato sedentario, 92 kg per 178 cm, vuole scendere a 82 kg. Mai fatto palestra, 3 giorni a settimana, 45-60 min.',
    expectation:
      'Deficit moderato (non estremo), proteine alte, durata del piano intorno ai 5 mesi (10 kg a 0,5 kg/sett.), scheda full body principiante con mese 1 di adattamento.',
    answers: base({
      age: 32,
      heightCm: 178,
      currentWeightKg: 92,
      goal: 'loseFat',
      targetWeightKg: 82,
      jobActivity: 'sedentary',
      dailySteps: '3000-5000',
      sleepHoursRange: '6-7',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
      freq_gym: '3',
      availableDays: '3',
      preferredProteins: ['chicken', 'turkey', 'eggs', 'yogurt'],
      preferredCarbs: ['rice', 'pasta', 'bread', 'oats'],
      usualBreakfast: 'cappuccino e brioche',
      usualLunch: 'pasta e pollo',
      usualDinner: 'insalata e uova',
    }),
    expect: { calories: 'deficit', gymSessions: 3 },
  },
  {
    id: 'giulia-mantenimento',
    name: 'Giulia, 27 anni — mantenimento, vegetariana',
    summary: 'Donna, 62 kg per 165 cm, vuole mantenere il peso e migliorare la forma. Intermedia, 4 allenamenti a settimana. Vegetariana.',
    expectation: 'Calorie vicine al mantenimento, nessuna carne né pesce nella dieta, split upper/lower a 4 giorni.',
    answers: base({
      age: 27,
      sex: 'female',
      heightCm: 165,
      currentWeightKg: 62,
      goal: 'maintainImprove',
      targetWeightKg: 62,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      dietaryPattern: 'vegetarian',
      preferredProteins: ['eggs', 'yogurt', 'dairy', 'legumes', 'tofu'],
      preferredCarbs: ['rice', 'oats', 'bread', 'legumes'],
      mealsSelected: ['colazione', 'spuntinoMattina', 'pranzo', 'cena'],
      morningSnackTime: '10:30',
      freq_gym: '4',
      availableDays: '4',
      gymExperience: '1-3years',
      gymSkillLevel: 'intermediate',
      focus_gym: 'hypertrophy',
    }),
    expect: {
      calories: 'maintenance',
      gymSessions: 4,
      forbiddenFoodIds: ['chicken-breast', 'turkey-breast', 'beef-lean', 'salmon', 'tuna-canned', 'bresaola', 'prosciutto-crudo'],
    },
  },
  {
    id: 'luca-massa',
    name: 'Luca, 22 anni — massa muscolare, esperto',
    summary: 'Studente magro (68 kg per 180 cm), vuole arrivare a 75 kg. Esperto, 5 allenamenti a settimana da 60-90 min, 5 pasti.',
    expectation: 'Surplus controllato, proteine ~2 g/kg, durata piano ~7 mesi (7 kg a 0,25 kg/sett.), split a 5 giorni senza mese di adattamento.',
    answers: base({
      age: 22,
      heightCm: 180,
      currentWeightKg: 68,
      goal: 'gainMuscle',
      targetWeightKg: 75,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      generalActivityLevel: 'moderate',
      mealsSelected: ['colazione', 'spuntinoMattina', 'pranzo', 'spuntinoPomeriggio', 'cena'],
      morningSnackTime: '10:30',
      afternoonSnackTime: '17:00',
      preferredProteins: ['chicken', 'beef', 'eggs', 'proteinPowder', 'yogurt'],
      preferredCarbs: ['rice', 'pasta', 'oats', 'potatoes', 'bread'],
      preferredFats: ['oliveOil', 'nuts', 'avocado'],
      freq_gym: '5',
      availableDays: '5',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      focus_gym: 'hypertrophy',
    }),
    expect: { calories: 'surplus', gymSessions: 5 },
  },
  {
    id: 'anna-ginocchio',
    name: 'Anna, 45 anni — dimagrimento con dolore al ginocchio e intolleranza al lattosio',
    summary: 'Donna, 78 kg per 162 cm, vuole scendere a 65 kg. Sedentaria, principiante, 2 allenamenti. Dolore al ginocchio, intollerante al lattosio.',
    expectation:
      'Nessun esercizio che carichi il ginocchio, nessun latticino, deficit prudente, durata lunga (13 kg → massimo del range), pochi esercizi per seduta.',
    answers: base({
      age: 45,
      sex: 'female',
      heightCm: 162,
      currentWeightKg: 78,
      goal: 'loseFat',
      targetWeightKg: 65,
      jobActivity: 'sedentary',
      dailySteps: 'lt3000',
      sleepHoursRange: '5-6',
      sleepQuality: 2,
      allergiesIntolerances: 'Sono intollerante al lattosio',
      preferredProteins: ['chicken', 'eggs', 'fish', 'yogurt', 'dairy'],
      freq_gym: '2',
      availableDays: '2',
      sessionDuration: '30-45',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
      hasPain: 'yes',
      painDetails: 'Mi fa male il ginocchio destro quando salgo le scale',
    }),
    expect: {
      calories: 'deficit',
      gymSessions: 2,
      avoidAreas: ['knee'],
      forbiddenFoodIds: ['greek-yogurt', 'cottage-cheese', 'ricotta', 'skyr', 'whey-protein', 'milk-semi', 'mozzarella', 'parmesan'],
    },
  },
  {
    id: 'paolo-runner',
    name: 'Paolo, 38 anni — solo corsa, resistenza',
    summary: 'Runner amatoriale, 72 kg per 176 cm. Corre 4 volte a settimana, nessuna palestra, vuole migliorare la resistenza.',
    expectation: 'Nessuna seduta di palestra, 4 uscite di corsa varie (facili, medio, lungo), carboidrati abbondanti, calorie di mantenimento.',
    answers: base({
      age: 38,
      heightCm: 176,
      currentWeightKg: 72,
      goal: 'improveEndurance',
      targetWeightKg: 72,
      jobActivity: 'standing',
      dailySteps: '8000-12000',
      activitiesPracticed: ['running'],
      freq_running: '4',
      focus_running: 'endurance',
      availableDays: '4',
      sessionDuration: '45-60',
      trainingLocation: 'outdoor',
      gymExperience: undefined,
      gymSkillLevel: undefined,
      freq_gym: undefined,
      focus_gym: undefined,
      gymSplitPreference: undefined,
    }),
    expect: { calories: 'maintenance', gymSessions: 0, runSessions: 4 },
  },
  {
    id: 'sara-vegana-casa',
    name: 'Sara, 30 anni — massa, vegana, allena a casa',
    summary: 'Donna, 58 kg per 168 cm, vuole mettere massa fino a 62 kg. Vegana, si allena a casa con manubri ed elastici, 3 volte a settimana.',
    expectation: 'Dieta senza alcun prodotto animale, proteine vegetali (tofu, legumi), solo esercizi eseguibili con manubri/elastici/corpo libero.',
    answers: base({
      age: 30,
      sex: 'female',
      heightCm: 168,
      currentWeightKg: 58,
      goal: 'gainMuscle',
      targetWeightKg: 62,
      jobActivity: 'seatedMobile',
      dietaryPattern: 'vegan',
      preferredProteins: ['legumes', 'tofu', 'proteinPowder'],
      preferredCarbs: ['rice', 'pasta', 'oats', 'legumes'],
      preferredFats: ['oliveOil', 'nuts', 'avocado'],
      freq_gym: '3',
      availableDays: '3',
      sessionDuration: '45-60',
      trainingLocation: 'home',
      equipment: ['dumbbells', 'bands'],
      gymExperience: '3-12months',
      gymSkillLevel: 'beginner',
      focus_gym: 'hypertrophy',
    }),
    expect: {
      calories: 'surplus',
      gymSessions: 3,
      forbiddenFoodIds: [
        'chicken-breast', 'turkey-breast', 'beef-lean', 'salmon', 'tuna-canned', 'eggs', 'egg-whites', 'greek-yogurt',
        'cottage-cheese', 'ricotta', 'whey-protein', 'skyr', 'mozzarella', 'parmesan', 'milk-semi', 'honey', 'bresaola', 'prosciutto-crudo',
      ],
    },
  },
  {
    id: 'roberto-schiena',
    name: 'Roberto, 58 anni — salute generale, mal di schiena',
    summary: 'Uomo, 90 kg per 175 cm, lavoro in piedi. Vuole stare meglio. Principiante, 2 allenamenti. Mal di schiena lombare.',
    expectation: 'Nessun esercizio che carichi la zona lombare (stacchi, rematori, squat pesanti), carichi prudenti, calorie vicine al mantenimento.',
    answers: base({
      age: 58,
      heightCm: 175,
      currentWeightKg: 90,
      goal: 'generalHealth',
      targetWeightKg: 85,
      jobActivity: 'standing',
      dailySteps: '5000-8000',
      freq_gym: '2',
      availableDays: '2',
      sessionDuration: '30-45',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'technique',
      hasPain: 'yes',
      painDetails: 'Ho spesso male alla schiena, zona lombare',
    }),
    expect: { gymSessions: 2, avoidAreas: ['lowerBack'] },
  },
  {
    id: 'elena-piccola',
    name: 'Elena, 35 anni — dimagrimento, corporatura piccola',
    summary: 'Donna, 50 kg per 155 cm, vuole scendere a 47 kg. Sedentaria, 3 allenamenti.',
    expectation: 'Il target calorico non deve mai scendere sotto il minimo di sicurezza (1200 kcal) e il deficit non deve essere aggressivo.',
    answers: base({
      age: 35,
      sex: 'female',
      heightCm: 155,
      currentWeightKg: 50,
      goal: 'loseFat',
      targetWeightKg: 47,
      jobActivity: 'sedentary',
      dailySteps: 'lt3000',
      sleepHoursRange: '6-7',
      gymExperience: '3-12months',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
    }),
    expect: { calories: 'deficit', gymSessions: 3 },
  },
  {
    id: 'davide-obeso',
    name: 'Davide, 28 anni — obesità, obiettivo molto lontano',
    summary: 'Uomo, 125 kg per 185 cm, lavoro fisico, vuole arrivare a 95 kg (−30 kg). Principiante, 4 allenamenti.',
    expectation: 'Piano al massimo della durata (12 mesi), deficit sostenibile, proteine calcolate in modo non eccessivo rispetto al peso reale, nessuna scheda estrema.',
    answers: base({
      age: 28,
      heightCm: 185,
      currentWeightKg: 125,
      goal: 'loseFat',
      targetWeightKg: 95,
      jobActivity: 'active',
      dailySteps: '8000-12000',
      freq_gym: '4',
      availableDays: '4',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
    }),
    expect: { calories: 'deficit', gymSessions: 4 },
  },
  {
    id: 'chiara-ibrida',
    name: 'Chiara, 25 anni — palestra + corsa, giorni insufficienti',
    summary: 'Donna, 60 kg per 168 cm. Vorrebbe 3 palestra + 3 corsa ma ha solo 4 giorni disponibili. Obiettivo dimagrimento.',
    expectation: 'Il piano deve rispettare i 4 giorni disponibili (non 6 sedute), bilanciando palestra e corsa, senza mettere due sedute lo stesso giorno.',
    answers: base({
      age: 25,
      sex: 'female',
      heightCm: 168,
      currentWeightKg: 60,
      goal: 'loseFat',
      targetWeightKg: 56,
      jobActivity: 'seatedMobile',
      dailySteps: '8000-12000',
      activitiesPracticed: ['gym', 'running'],
      freq_gym: '3',
      freq_running: '3',
      focus_running: 'fatLoss',
      focus_gym: 'fatLoss',
      availableDays: '4',
      gymExperience: '1-3years',
      gymSkillLevel: 'intermediate',
    }),
    expect: { calories: 'deficit' },
  },
  {
    id: 'andrea-solo-dieta',
    name: 'Andrea, 40 anni — solo dieta',
    summary: 'Uomo, 80 kg per 180 cm, vuole solo un piano alimentare per dimagrire a 75 kg. Non usa la parte allenamento.',
    expectation: 'Il piano di allenamento non deve esistere, la dieta deve essere completa; le schermate di allenamento devono gestire l’assenza del piano.',
    answers: base({
      mode: 'diet',
      age: 40,
      heightCm: 180,
      currentWeightKg: 80,
      goal: 'loseFat',
      targetWeightKg: 75,
      jobActivity: 'sedentary',
      activitiesPracticed: undefined,
      freq_gym: undefined,
      gymExperience: undefined,
      gymSkillLevel: undefined,
      gymSplitPreference: undefined,
      focus_gym: undefined,
      availableDays: undefined,
      sessionDuration: undefined,
      trainingLocation: undefined,
      hasPain: undefined,
      cannotDoExercises: undefined,
      recentInjuries: undefined,
    }),
    expect: { calories: 'deficit', noTraining: true },
  },
  {
    id: 'ilaria-solo-allenamento',
    name: 'Ilaria, 29 anni — solo allenamento, forza',
    summary: 'Donna, 64 kg per 170 cm, vuole solo la scheda per aumentare la forza. 4 giorni, esperta.',
    expectation: 'Il piano alimentare non deve esistere, la scheda deve avere schemi di forza (poche ripetizioni, recuperi lunghi).',
    answers: base({
      mode: 'training',
      age: 29,
      sex: 'female',
      heightCm: 170,
      currentWeightKg: 64,
      goal: 'gainStrength',
      targetWeightKg: 66,
      jobActivity: 'seatedMobile',
      freq_gym: '4',
      availableDays: '4',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      focus_gym: 'strength',
      mealsSelected: undefined,
      breakfastTime: undefined,
      lunchTime: undefined,
      dinnerTime: undefined,
      eatingOut: undefined,
      dietaryPattern: undefined,
      allergiesIntolerances: undefined,
      excludedFoods: undefined,
      includedFoods: undefined,
      preferredProteins: undefined,
      preferredCarbs: undefined,
      preferredFats: undefined,
      coffeeIntake: undefined,
      alcoholIntake: undefined,
    }),
    expect: { calories: 'surplus', noDiet: true, gymSessions: 4 },
  },
  {
    id: 'giorgio-celiaco',
    name: 'Giorgio, 34 anni — celiaco e allergico alla frutta secca',
    summary: 'Uomo, 82 kg per 181 cm, mantenimento. Celiaco (niente glutine) e allergico alla frutta secca e alle noci. 3 allenamenti.',
    expectation: 'Nessuna fonte di glutine (pasta, pane, couscous…) e nessuna frutta secca in nessun pasto del piano.',
    answers: base({
      age: 34,
      heightCm: 181,
      currentWeightKg: 82,
      goal: 'maintainImprove',
      targetWeightKg: 82,
      allergiesIntolerances: 'Sono celiaco, niente glutine. Allergia a frutta secca e noci',
      preferredCarbs: ['pasta', 'bread', 'rice', 'potatoes'],
      preferredFats: ['nuts', 'oliveOil'],
      freq_gym: '3',
    }),
    expect: {
      calories: 'maintenance',
      gymSessions: 3,
      forbiddenFoodIds: ['pasta', 'bread-wholegrain', 'bread-white', 'couscous', 'almonds', 'walnuts', 'peanut-butter'],
    },
  },
  {
    id: 'valentina-spalla',
    name: 'Valentina, 31 anni — spalla infortunata, preferisce Push/Pull/Legs',
    summary: 'Donna, 66 kg per 172 cm, ipertrofia. Esperta, 5 giorni, vuole Push/Pull/Legs. Infortunio recente alla spalla sinistra.',
    expectation: 'Nessun esercizio che sovraccarichi la spalla (panca, military press, dip, alzate…), anche se la preferenza è PPL: la sicurezza prevale.',
    answers: base({
      age: 31,
      sex: 'female',
      heightCm: 172,
      currentWeightKg: 66,
      goal: 'gainMuscle',
      targetWeightKg: 69,
      freq_gym: '5',
      availableDays: '5',
      sessionDuration: '60-90',
      gymExperience: '3plusYears',
      gymSkillLevel: 'expert',
      gymSplitPreference: 'pushPullLegs',
      focus_gym: 'hypertrophy',
      recentInjuries: 'yes',
      recentInjuriesDetails: 'Lesione alla cuffia dei rotatori, spalla sinistra, tre mesi fa',
    }),
    expect: { calories: 'surplus', gymSessions: 5, avoidAreas: ['shoulder'] },
  },
  {
    id: 'franco-pensionato',
    name: 'Franco, 67 anni — salute, sedentario, un solo giorno',
    summary: 'Uomo, 78 kg per 170 cm, pensionato. Può allenarsi 1 volta a settimana, 30 minuti, principiante.',
    expectation: 'Una sola seduta a settimana (full body, 3 esercizi), piano non invasivo, calorie di mantenimento.',
    answers: base({
      age: 67,
      heightCm: 170,
      currentWeightKg: 78,
      goal: 'generalHealth',
      targetWeightKg: 76,
      jobActivity: 'sedentary',
      dailySteps: '3000-5000',
      freq_gym: '1',
      availableDays: '1',
      sessionDuration: 'lt30',
      gymExperience: 'never',
      gymSkillLevel: 'beginner',
      focus_gym: 'technique',
    }),
    expect: { calories: 'maintenance', gymSessions: 1 },
  },
  {
    id: 'tommaso-saltuario',
    name: 'Tommaso, 35 anni — si allena una volta ogni due settimane',
    summary: 'Uomo, 80 kg per 178 cm, mantenimento. In palestra va "una volta ogni 2 settimane" e ha 3 giorni disponibili.',
    expectation: 'Il piano non deve inventare 3 sedute a settimana per chi ne fa meno di una; il fabbisogno e il piano devono contare lo stesso numero di allenamenti.',
    answers: base({
      age: 35,
      currentWeightKg: 80,
      goal: 'maintainImprove',
      targetWeightKg: 80,
      freq_gym: 'biweekly',
      availableDays: '3',
      gymExperience: '1-3years',
      gymSkillLevel: 'intermediate',
    }),
    expect: { calories: 'maintenance' },
  },
  {
    id: 'nina-senza-peso-obiettivo',
    name: 'Nina, 33 anni — dimagrimento senza peso obiettivo',
    summary: 'Donna, 70 kg per 166 cm, vuole dimagrire ma lascia vuoto il peso obiettivo (domanda facoltativa).',
    expectation: 'Il profilo e le schermate non devono usare un peso obiettivo inventato; la durata del piano deve avere senso anche senza obiettivo.',
    answers: base({
      age: 33,
      sex: 'female',
      heightCm: 166,
      currentWeightKg: 70,
      goal: 'loseFat',
      targetWeightKg: undefined,
      jobActivity: 'seatedMobile',
      gymExperience: '3-12months',
      gymSkillLevel: 'beginner',
      focus_gym: 'fatLoss',
    }),
    expect: { calories: 'deficit', gymSessions: 3 },
  },
  {
    id: 'omar-ex-allenamento',
    name: 'Omar, 41 anni — ora solo dieta, ma aveva già fatto il questionario con allenamento',
    summary: 'Uomo, 85 kg per 180 cm. Rifà il questionario scegliendo solo dieta; nelle risposte restano i dati di allenamento di prima (4 allenamenti di palestra).',
    expectation: 'Con modalità "solo dieta" le vecchie risposte di allenamento non devono influenzare né il fabbisogno né l’alternanza giorni allenamento/riposo.',
    answers: base({
      mode: 'diet',
      age: 41,
      currentWeightKg: 85,
      goal: 'loseFat',
      targetWeightKg: 78,
      activitiesPracticed: ['gym'],
      freq_gym: '4',
      availableDays: '4',
    }),
    expect: { calories: 'deficit', noTraining: true },
  },
];
